---
title: "Reproduce_Fujikawa"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reproduce_Fujikawa}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(baskexact)

### Single-Stage Design
design1 <- setupOneStageBasket(k = 3, shape1 = 1, shape2 = 1, theta0 = 0.2)

# Figure 1
basket_test(design1, n = 15, r = c(1, 5, 7), lambda = 0.99, 
  weight_fun = weights_fujikawa, weight_params = list(epsilon = 2, tau = 0.5,
    logbase = exp(1)))

## theta = (0.2, 0.2, 0.2)
# Proposed design (i)
toer(
  design = design1, n = 24, lambda = 0.99,
  weight_fun = weights_fujikawa, weight_params = list(epsilon = 2, tau = 0,
  logbase = exp(1), prune = FALSE), results = "group"
)

# Proposed design (ii)
toer(
  design = design1, n = 24, lambda = 0.99,
  weight_fun = weights_fujikawa, weight_params = list(epsilon = 2, tau = 0.5,
  logbase = exp(1), prune = FALSE), results = "group"
)

### Single-Stage Design
design2 <- setupTwoStageBasket(k = 3, shape1 = 1, shape2 = 1, theta0 = 0.2)

## theta = (0.2, 0.2, 0.2)
# Proposed design (i)
toer(
  design = design2, n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0, epsilon = 2),
  results = "group"
)

# Proposed design (ii)
toer(
  design = design2, n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0.5, epsilon = 2),
  results = "group"
)

## theta = c(0.5, 0.2, 0.2)
# Proposed design (i)
pow(
  design = design2, theta1 = c(0.5, 0.2, 0.2), n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0, epsilon = 2),
  results = "group"
)

# Proposed design (ii)
pow(
  design = design2, theta1 = c(0.5, 0.2, 0.2), n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0.5, epsilon = 2),
  results = "group"
)

## theta = c(0.5, 0.5, 0.2)
# Proposed design (i)
pow(
  design = design2, theta1 = c(0.5, 0.5, 0.2), n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0, epsilon = 2),
  results = "group"
)

# Proposed design (ii)
pow(
  design = design2, theta1 = c(0.5, 0.5, 0.2), n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0.5, epsilon = 2),
  results = "group"
)

## theta = c(0.5, 0.5, 0.5)
# Proposed design (i)
pow(
  design = design2, theta1 = c(0.5, 0.5, 0.5), n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0, epsilon = 2),
  results = "group"
)

# Proposed design (ii)
pow(
  design = design2, theta1 = c(0.5, 0.5, 0.5), n = 24, n1 = 15, lambda = 0.99, 
  interim_fun = interim_postpred, interim_params = list(prob_futstop = 0.1,
    prob_effstop = 0.9), weight_fun = weights_fujikawa,
  weight_params = list(logbase = exp(1), tau = 0.5, epsilon = 2),
  results = "group"
)
```
