# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weight_beta <- function(k, weights, shape) {
    .Call(`_baskexact_weight_beta`, k, weights, shape)
}

